# === Tmux Configuration ===
# Rosé Pine theme
# Prefix: Ctrl+A

unbind -a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -ga terminal-features ",xterm-256color:RGB"
set -g default-terminal "screen-256color"
set -g update-environment "COLORTERM TERM"
set -g default-shell /bin/zsh
set -g allow-passthrough on
set -g history-limit 100000
set -g base-index 1
set -g display-panes-time 1000
set -g display-time 1000
set -g renumber-windows on
set -g set-titles on
set -g allow-rename off
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
set -g mouse off
set -g escape-time 0
set -g repeat-time 0
set -g focus-events on
set -g detach-on-destroy off

setw -g mode-keys vi
setw -g xterm-keys on
setw -g aggressive-resize on
setw -g pane-base-index 1
setw -g automatic-rename on
setw -g monitor-activity off

bind c new-window
bind w choose-window
bind - split-window -v
bind \\ split-window -h
bind -n C-j previous-window
bind -n C-k next-window
bind s new-session
bind d detach
bind [ switch-client -p
bind ] switch-client -n
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind x kill-pane
bind C-x run-shell "tmux kill-server"
bind X source-file ~/.config/tmux/tmux.conf\; display "Reloaded!"
bind f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind C-d neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/.personal/todo.md"
bind v copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind C-f display-popup -E "tmux list-buffers | fzf --reverse | cut -d: -f1 | xargs tmux paste-buffer -b"
bind S command-prompt -p "Session:" "new-session -A -s '%%'"

set -g status-bg '#191724'
set -g status-fg '#e0def4'
set -g status-right " #[fg=#ebbcba]%H:%M   #[fg=#c4a7e7]%d.%m.%Y"
set -g status-right-length 80
set -g status-left ' #[fg=#c4a7e7]#S '
set -g status-left-length 20
set -g status-interval 2
set -g status-position bottom

setw -g window-status-current-style 'fg=#191724 bg=#c4a7e7 bold'
setw -g window-status-current-format ' #I #[fg=#191724]#W#[fg=#191724]#F '
setw -g window-status-style 'fg=#c4a7e7 bg=#191724 bold'
setw -g window-status-format ' #I #[fg=#e0def4]#W #[fg=#c4a7e7]#F '
setw -g window-status-bell-style 'fg=#191724 bg=#ff4c4c bold'

set -g pane-border-style 'fg=#6e6a86'
set -g pane-active-border-style 'fg=#c4a7e7'
set -g pane-border-format '#{pane_index} #{pane_current_command}'

setw -g clock-mode-colour '#c4a7e7'
setw -g mode-style 'fg=#191724 bg=#c4a7e7 bold'
set -g message-style 'fg=#191724 bg=#c4a7e7 bold'
